version: "3"
services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  tickets-service:
    build: ./tickets-service
    image: tickets-service:latest
    container_name: tickets-service
    ports:
      - "8080:8080"
    command: >
      sh -c "sequelize-cli db:migrate && node dist/main.js"
    depends_on:
      - postgres

volumes:
  db-data: